# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Chloe Eather

this-makefile := $(lastword $(MAKEFILE_LIST))
abs_srctree := $(realpath $(dir $(this-makefile)))
abs_output = $(CURDIR)

$(if $(filter __%, $(MAKECMDGOALS)), \
	$(error targets prefixed with '__' are for internal use only))

PHONY += __all
__all:

ifneq ($(sub_make_done),1)
MAKEFLAGS += rR

ifeq ("$(origin O)", "command line")
KBUILD_OUTPUT := $(O)
endif

ifneq ($(KBUILD_OUTPUT),)
$(shell mkdir -p "$(KBUILD_OUTPUT)")
abs_output := $(realpath $(KBUILD_OUTPUT))
$(if $(abs_output),,$(error Failed to create output directory "$(KBUILD_OUTPUT)"))
endif

ifneq ($(words $(subst :, ,$(abs_srctree))), 1)
$(error Source directory cannot contain spaces or colons)
endif

export sub_make_done := 1
endif # !sub_make_done

ifeq ($(abs_output),$(CURDIR))
no-print-directory := --no-print-directory
else
need-sub-make := 1
endif

ifeq ($(filter --no-print-directory, $(MAKEFLAGS)),)
need-sub-make := 1
endif

ifeq ($(need-sub-make),1)
PHONY += $(MAKECMDGOALS) __sub-make
$(filter-out $(this-makefile), $(MAKECMDGOALS)) __all: __sub-make
	@:

__sub-make:
	$(MAKE) $(no-print-directory) -C $(abs_output) -f$(abs_srctree)/Makefile $(MAKECMDGOALS)

else # need-sub-make
ifeq ($(abs_srctree),$(CURDIR))
building_out_of_srctree :=
else
export building_out_of_srctree := 1
endif

srcroot := $(abs_srctree)

ifeq ($(srcroot),$(CURDIR))
srcroot := .
else ifeq ($(srcroot),$(dir $(CURDIR)))
srcroot := ..
endif

export srctree := $(srcroot)

ifdef building_out_of_srctree
export VPATH := $(srcroot)
else
VPATH :=
endif

-include config.mk

TARGET          ?= x86_64-elf
CROSS_COMPILE   ?= x86_64-elf-
BUILD_TYPE      ?= Release
export TARGET CROSS_COMPILE BUILD_TYPE

HOSTCC          := gcc
HOSTCXX         := g++
HOSTPKG_CONFIG  := pkg-config
AS              := $(CROSS_COMPILE)as
LD              := $(CROSS_COMPILE)ld
CC              := $(CROSS_COMPILE)gcc
CPP             := $(CC) -E
AR              := $(CROSS_COMPILE)ar
NM              := $(CROSS_COMPILE)nm
STRIP           := $(CROSS_COMPILE)strip
OBJCOPY         := $(CROSS_COMPILE)objcopy
OBJDUMP         := $(CROSS_COMPILE)objdump
AWK             := awk
BASH            := bash
LEX             := flex
YACC            := bison

CFLAGS := -mno-red-zone -mno-sse -mno-mmx -mno-sse2 -fno-exceptions -fno-asynchronous-unwind-tables -Wall -Wextra -Werror
LDFLAGS := -nostdlib -nostartfiles

ifeq ("$(BUILD_TYPE)","Release")
CFLAGS += -O2
else ifeq ("$(BUILD_TYPE)","Debug")
CFLAGS += -ggdb
endif

export HOSTCC HOSTCXX HOSTPKG_CONFIG AS LD CC CPP AR NM STRIP OBJCOPY OBJDUMP
export AWK BASH LEX YACC CFLAGS LDFLAGS

SUBPROJECTS := ceek libc
CLEAN_SUBPROJECTS := $(addprefix clean-,$(SUBPROJECTS))
CLEAN_MRPROPER := $(addprefix mrproper-,$(SUBPROJECTS))

PHONY += outputmakefile
ifdef building_out_of_srctree
outputmakefile:
	ln -fsn $(srcroot) source
	{ \
	echo "# Automatically generated by $(abs_srctree)/Makefile: don't edit"; \
	echo "export KBUILD_OUTPUT = $(CURDIR)"; \
	echo "include $(abs_srctree)/Makefile"; \
	} > Makefile
	test -e .gitignore || \
	{ echo "#this is a build directory"; echo "*"; } > .gitignore
endif

PHONY += all
all: __all

__all: outputmakefile $(CONFIG_MK) subprojects

config.mk:
	{ \
	echo "TARGET ?= $(TARGET)"; \
	echo "CROSS_COMPILE ?= $(CROSS_COMPILE)"; \
	echo "BUILD_TYPE ?= $(BUILD_TYPE)"; \
	} > config.mk

PHONY += subprojects $(SUBPROJECTS)
subprojects: $(SUBPROJECTS)


libk:
	$(MAKE) -f$(srctree)/libc/Makefile O="libc" srctree="$(srctree)" libk

ceek: libk
	$(MAKE) -f$(srctree)/ceek/Makefile O="ceek" srctree="$(srctree)" ceek

libc: ceek
	$(MAKE) -f$(srctree)/libc/Makefile O="libc" srctree="$(srctree)" libc

PHONY += clean $(CLEAN_SUBPROJECTS)
clean: $(CLEAN_SUBPROJECTS)

$(CLEAN_SUBPROJECTS):
	$(MAKE) -f$(srctree)/$(subst clean-,,$@)/Makefile O="$(subst clean-,,$@)" srctree="$(srctree)" clean

PHONY += mrproper $(MRPROPER_SUBPROJECTS)
mrproper: $(MRPROPER_SUBPROJECTS)
	rm -rf config.mk Makefile

$(MRPROPER_SUBPROJECTS):
	$(MAKE) -f$(srctree)/$(subst mrproper-,,$@)/Makefile O=$(subst mrproper-,,$@) mrproper
endif # need-sub-make

.PHONY: $(PHONY)

