# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Chloe Eather

this-makefile := $(lastword $(MAKEFILE_LIST))
abs_srctree := $(realpath $(dir $(this-makefile)))
abs_objtree = $(CURDIR)

srctree ?= $(abs_srctree)
objtree ?= $(abs_objtree)

$(if $(filter __%, $(MAKECMDGOALS)), \
    $(error targets prefixed with '__' are for internal use only))

PHONY += __all
__all:

ifneq ($(sub_make_done),1)
MAKEFLAGS += rR --no-print-directory

ifeq ("$(origin O)", "command line")
KBUILD_OUTPUT := $(O)
endif

ifneq ($(KBUILD_OUTPUT),)
    $(shell mkdir -p "$(KBUILD_OUTPUT)")
    abs_objtree := $(realpath $(KBUILD_OUTPUT))
    $(if $(abs_objtree),,$(error Failed to create output directory "$(KBUILD_OUTPUT)"))
    objtree := $(abs_objtree)
endif

ifneq ($(words $(subst :, ,$(abs_srctree))), 1)
    $(error Source directory cannot contain spaces or colons)
endif

export sub_make_done := 1
endif # !sub_make_done

need-sub-make :=
ifneq ($(realpath $(abs_objtree)),$(realpath $(CURDIR)))
    need-sub-make := 1
endif

ifeq ($(need-sub-make),1)
PHONY += $(MAKECMDGOALS) __sub-make
$(filter-out $(this-makefile), $(MAKECMDGOALS)) __all: __sub-make
	@:

__sub-make:
	$(MAKE) -C "$(abs_objtree)" -f"$(abs_srctree)/Makefile" \
		srctree="$(srctree)" objtree="$(objtree)" \
		KBUILD_OUTPUT="$(KBUILD_OUTPUT)" $(MAKECMDGOALS)

else # need-sub-make
ifeq ($(abs_srctree),$(CURDIR))
    building_out_of_srctree :=
else
    export building_out_of_srctree := 1
endif

clean-targets := clean mrproper

clean_build :=
mixed-build :=

ifneq ($(filter $(clean-targets),$(MAKECMDGOALS)),)
    clean-build := 1
    ifneq ($(filter-out $(clean-targets),$(MAKECMDGOALS)),)
        mixed-build := 1
    endif
endif

ifdef mixed-build
PHONY += $(MAKECMDGOALS) __build_one_by_one
$(MAKECMDGOALS): __build_one_by_one

__build_one_by_one:
	set -e; \
	for i in $(MAKECMDGOALS); do \
		$(MAKE) -f$(srctree)/Makefile $$i; \
	done

else # mixed-build

OBJTREE_MARKER := $(srctree)/.objtree

TARGET          ?= x86_64-elf
CROSS_COMPILE   ?= x86_64-elf-
BUILD_TYPE      ?= Release
export TARGET CROSS_COMPILE BUILD_TYPE

HOSTCC          := gcc
HOSTCXX         := g++
HOSTPKG_CONFIG  := pkg-config
AS              := $(CROSS_COMPILE)as
LD              := $(CROSS_COMPILE)ld
CC              := $(CROSS_COMPILE)gcc
CPP             := $(CC) -E
AR              := $(CROSS_COMPILE)ar
NM              := $(CROSS_COMPILE)nm
STRIP           := $(CROSS_COMPILE)strip
OBJCOPY         := $(CROSS_COMPILE)objcopy
OBJDUMP         := $(CROSS_COMPILE)objdump
AWK             := awk
BASH            := bash

WARNINGFLAGS := -Wall -Wextra -Werror -Wpedantic -Wswitch-enum
CFLAGS := -mno-red-zone -mno-sse -mno-mmx -mno-sse2 -fno-builtin \
		  -std=c11 -fno-strict-aliasing -fno-pic -mcmodel=kernel\
		  $(WARNINGFLAGS) -I"$(srctree)/include"
ASFLAGS ?= $(CFLAGS)
LDFLAGS := -no-pie -nostdlib -nostartfiles

ifeq ("$(BUILD_TYPE)","Release")
CFLAGS += -O2
LDFLAGS += -O2
else ifeq ("$(BUILD_TYPE)","Debug")
CFLAGS += -g3 -O0 -fno-omit-frame-pointer
LDFLAGS += -g -O0
endif

export HOSTCC HOSTCXX HOSTPKG_CONFIG AS LD CC CPP AR NM STRIP OBJCOPY OBJDUMP
export AWK BASH DEPFLAGS WARNINGFLAGS CFLAGS ASFLAGS LDFLAGS

PHONY += outputmakefile
ifdef building_out_of_srctree
outputmakefile:
	@if [ -f "$(OBJTREE_MARKER)" ] && [ "$$(cat $(OBJTREE_MARKER))" != "$(abs_objtree)" ]; then \
		echo >&2 "***"; \
		echo >&2 "*** $(abs_objtree)"; \
		cat $(OBJTREE_MARKER); \
		echo >&2 "***"; \
		echo >&2 "*** Out of source build exists, please run 'make mrproper' in"; \
		echo >&2 "*** '$(abs_srctree)' to clean or build from existing dir"; \
		echo >&2 "***"; \
		false; \
	fi
	@{ \
		echo "# Automatically generated by $(abs_srctree)/Makefile: don't edit"; \
		echo "export KBUILD_OUTPUT := $(abs_objtree)"; \
		echo "export BUILD_TYPE := $(BUILD_TYPE)"; \
		echo "include $(abs_srctree)/Makefile"; \
	} > Makefile
	@echo "Generated build stub Makefile"
	@test -e .gitignore || \
	{ echo "#this is a build directory"; echo "*"; } > .gitignore

__all: $(OBJTREE_MARKER)
endif

build := -f $(srctree)/scripts/Makefile.build obj
clean := -f $(srctree)/scripts/Makefile.clean obj

CEEK := $(objtree)/ceek.elf
CEEK_DBG := $(objtree)/ceek.debug
CEEK_STR := $(objtree)/ceek.x86_64
CEEK_MAP := $(objtree)/ceek.map

core-dirs := arch/x86 boot io kernel lib
core-objs := $(addprefix $(objtree)/,$(addsuffix /built-in.o,$(core-dirs)))

PHONY += all
all: __all

__all: outputmakefile $(CEEK) $(CEEK_DBG) $(CEEK_STR)

$(OBJTREE_MARKER):
	@echo "$(abs_objtree)" > $@
	@echo "Generated $(OBJTREE_MARKER)"

$(objtree)/%/built-in.o:
	$(MAKE) $(build)=$* srctree="$(srctree)" objtree="$(objtree)"

.PHONY: $(core-dirs)
$(core-dirs):
	$(MAKE) $(build)=$@ srctree="$(srctree)" objtree="$(objtree)"

$(CEEK): $(core-objs)
	$(CC) $(LDFLAGS) -Wl,-T,$(srctree)/link.ld,-z,max-page-size=4096 \
		-Wl,--Map=$(CEEK_MAP) -o $@ $(core-objs)


$(CEEK_DBG): $(CEEK)
	$(OBJCOPY) --only-keep-debug $< $@

$(CEEK_STR): $(CEEK) $(CEEK_DBG)
	$(STRIP) --strip-debug --strip-unneeded -o $(CEEK_STR) $(CEEK)
	$(OBJCOPY) --add-gnu-debuglink=$(CEEK_DBG) $(CEEK_STR)

PHONY += clean
clean:
	rm -f $(CEEK) $(CEEK_DBG) $(CEEK_STR) $(CEEK_MAP)
	@for d in $(core-dirs); do \
		$(MAKE) $(clean)=$$d srctree="$(srctree)" objtree="$(objtree)"; \
	done

PHONY += mrproper
mrproper: clean
	rm -f $(srctree)/.objtree
	if [ "$(objtree)" != "$(srctree)" ]; then rm -rf $(objtree); fi

endif # mixed-build
endif # need-sub-make

.PHONY: $(PHONY)

