# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Chloe Eather

this-makefile := $(lastword $(MAKEFILE_LIST))
abs_srctree := $(realpath $(dir $(this-makefile)))
abs_objtree = $(CURDIR)

$(if $(filter __%, $(MAKECMDGOALS)), \
	$(error targets prefixed with '__' are for internal use only))

PHONY += __all
__all:

ifneq ($(sub_make_done),1)
MAKEFLAGS += rR

ifeq ("$(origin O)", "command line")
KBUILD_OUTPUT := $(O)
endif

ifneq ($(KBUILD_OUTPUT),)
$(shell mkdir -p "$(KBUILD_OUTPUT)")
abs_objtree := $(realpath $(KBUILD_OUTPUT))
$(if $(abs_objtree),,$(error Failed to create output directory "$(KBUILD_OUTPUT)"))
endif

ifneq ($(words $(subst :, ,$(abs_srctree))), 1)
$(error Source directory cannot contain spaces or colons)
endif

export sub_make_done := 1
endif # !sub_make_done

ifeq ($(abs_objtree),$(CURDIR))
no-print-directory := --no-print-directory
else
need-sub-make := 1
endif

ifeq ($(filter --no-print-directory, $(MAKEFLAGS)),)
need-sub-make := 1
endif

ifeq ($(need-sub-make),1)
PHONY += $(MAKECMDGOALS) __sub-make
$(filter-out $(this-makefile), $(MAKECMDGOALS)) __all: __sub-make
	@:

__sub-make:
	$(MAKE) $(no-print-directory) -C $(abs_objtree) \
		-f$(abs_srctree)/Makefile $(MAKECMDGOALS)

else # need-sub-make
ifeq ($(abs_srctree),$(CURDIR))
building_out_of_srctree :=
else
export building_out_of_srctree := 1
endif

srcroot := $(abs_srctree)

ifeq ($(srcroot),$(CURDIR))
srcroot := .
else ifeq ('$(srcroot)/','$(dir $(CURDIR))')
srcroot := ..
endif

export srctree := $(srcroot)

ifdef building_out_of_srctree
export VPATH := $(srcroot)
else
VPATH :=
endif

SUBPROJECTS := ceek libc
CLEAN_SUBPROJECTS := $(addprefix clean-,$(SUBPROJECTS))
MRPROPER_SUBPROJECTS := $(addprefix mrproper-,$(SUBPROJECTS))


compile_commands-targets := compile_commands
compile_commands-build :=

ifneq ($(filter $(compile_commands-targets),$(MAKECMDGOALS)),)
compile_commands-build := 1
endif

ifdef compile_commands-build
PHONY += $(MAKECMDGOALS) $(KBUILD_OUTPUT)/compile_commands.json
$(MAKECMDGOALS): $(KBUILD_OUTPUT)/compile_commands.json

$(KBUILD_OUTPUT)/compile_commands.json:
	bear --output $@ -- $(MAKE) -f$(srctree)/Makefile \
		$(filter-out $(compile_commands-targets),$(MAKECMDGOALS))

else # compile_commands-build
clean-targets := clean $(CLEAN_SUBPROJECTS) mrproper $(MRPROPER_SUBPROJECTS)

clean_build :=
mixed-build :=

ifneq ($(filter $(clean-targets),(MAKECMDGOALS)),)
clean-build := 1
ifneq ($(filter-out $(clean-targets),$(MAKECMDGOALS),)
mixed-build := 1
endif
endif

ifdef mixed-build
PHONY += $(MAKECMDGOALS) __build_one_by_one
$(MAKECMDGOALS): __build_one_by_one

__build_one_by_one:
	set -e; \
	for i in $(MAKECMDGOALS); do \
		$(MAKE) -f$(srctree)/Makefile $$i; \
	done

else # mixed-build

-include config.mk

TARGET          ?= x86_64-elf
CROSS_COMPILE   ?= x86_64-elf-
BUILD_TYPE      ?= Release
export TARGET CROSS_COMPILE BUILD_TYPE

HOSTCC          := gcc
HOSTCXX         := g++
HOSTPKG_CONFIG  := pkg-config
AS              := $(CROSS_COMPILE)as
LD              := $(CROSS_COMPILE)ld
CC              := $(CROSS_COMPILE)gcc
CPP             := $(CC) -E
AR              := $(CROSS_COMPILE)ar
NM              := $(CROSS_COMPILE)nm
STRIP           := $(CROSS_COMPILE)strip
OBJCOPY         := $(CROSS_COMPILE)objcopy
OBJDUMP         := $(CROSS_COMPILE)objdump
AWK             := awk
BASH            := bash

DEPFLAGS := -MMD -MD -MP
CFLAGS := -mno-red-zone -mno-sse -mno-mmx -mno-sse2 -fno-exceptions -fno-asynchronous-unwind-tables -Wall -Wextra -Werror $(DEPFLAGS)
LDFLAGS := -nostdlib -nostartfiles

ifeq ("$(BUILD_TYPE)","Release")
CFLAGS += -O2
else ifeq ("$(BUILD_TYPE)","Debug")
CFLAGS += -ggdb -Og -fno-omit-frame-pointer
endif

export HOSTCC HOSTCXX HOSTPKG_CONFIG AS LD CC CPP AR NM STRIP OBJCOPY OBJDUMP
export AWK BASH DEPFLAGS CFLAGS LDFLAGS

PHONY += outputmakefile
ifdef building_out_of_srctree
outputmakefile:
	@if [ -f $(srctree)/config.mk ]; then \
		echo >&2 "***"; \
		echo >&2 "*** The source tree is not clean, please run 'make mrproper' in"; \
		echo >&2 "*** '$(abs_srctree)' to clean"; \
		echo >&2 "***"; \
		false; \
	fi
	@{ \
		echo "# Automatically generated by $(abs_srctree)/Makefile: don't edit"; \
		echo "export KBUILD_OUTPUT = $(CURDIR)"; \
		echo "include $(abs_srctree)/Makefile"; \
	} > Makefile
	@echo "Generated build stub Makefile"
	@test -e .gitignore || \
	{ echo "#this is a build directory"; echo "*"; } > .gitignore
endif

PHONY += all
all: __all

__all: outputmakefile $(CONFIG_MK) subprojects

config.mk:
	@{ \
		echo "# Automatically generated by $(abs_srctree)/Makefile: don't edit"; \
		echo "TARGET ?= $(TARGET)"; \
		echo "CROSS_COMPILE ?= $(CROSS_COMPILE)"; \
		echo "BUILD_TYPE ?= $(BUILD_TYPE)"; \
	} > config.mk
	@echo "Generated $(KBUILD_OUTPUT)/config.mk"

PHONY += subprojects $(SUBPROJECTS)
subprojects: $(SUBPROJECTS)

libk:
	$(MAKE) -f$(srctree)/libc/Makefile O="libc" \
		srctree="$(srctree)" objtree="$(KBUILD_OUTPUT)" libk

ceek: libk
	$(MAKE) -f$(srctree)/ceek/Makefile O="ceek" \
		srctree="$(srctree)" objtree="$(KBUILD_OUTPUT)" ceek

libc: ceek
	$(MAKE) -f$(srctree)/libc/Makefile O="libc" \
		srctree="$(srctree)" objtree="$(KBUILD_OUTPUT)" libc

PHONY += clean $(CLEAN_SUBPROJECTS)
clean: $(CLEAN_SUBPROJECTS)

$(CLEAN_SUBPROJECTS):
	@$(MAKE) -f$(srctree)/$(subst clean-,,$@)/Makefile \
		O="$(subst clean-,,$@)" \
		srctree="$(srctree)" objtree="$(KBUILD_OUTPUT)" clean

PHONY += mrproper $(MRPROPER_SUBPROJECTS)
mrproper: clean $(MRPROPER_SUBPROJECTS)
	rm -rf config.mk
	@if [ "$(KBUILD_OUTPUT)" != "$(srctree)" ]; then \
		if [ -f "$(KBUILD_OUTPUT)/Makefile" ]; then \
			rm -f "$(KBUILD_OUTPUT)/Makefile"; \
			echo "Removing build stub Makefile"; \
		fi; \
		if [ -f "$(KBUILD_OUTPUT)/compile_command.json" ]; then \
			rm -f "$(KBUILD_OUTPUT)/compile_command.json"; \
			echo "Removing compile_command.json"; \
		fi; \
	fi;

$(MRPROPER_SUBPROJECTS):
	$(MAKE) -f$(srctree)/$(subst mrproper-,,$@)/Makefile \
		O=$(subst mrproper-,,$@) \
		srctree="$(srctree)" objtree="$(KBUILD_OUTPUT)" mrproper

DEPFILES := $(wildcard $(KBUILD_OUTPUT)/.deps/*.d)
include $(DEPFILES)

endif # mixed-build
endif # compile_commands-build
endif # need-sub-make

.PHONY: $(PHONY)

